schema_version: 1

context:
  version: "0.1.31"
  python_min: "3.11"

package:
  name: kagglesdk
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kagglesdk/kagglesdk-${{ version }}.tar.gz
  sha256: 705d90b5ebaceca9d4b0b5048087395c6c10fb0cb196e51b75731b79229266bc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - protobuf

tests:
  - python:
      imports:
        - kagglesdk
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/Kaggle/kagglesdk
  repository: https://github.com/Kaggle/kagglesdk
  summary: Bindings to access kaggle's external-facing APIs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
